import { CardDef } from './types';

export const CARD_DEFS: CardDef[] = [
  // === 素材畑 (生産建物) ===
  {
    id: 'indigo_plant',
    name: 'ハーブ園',
    type: 'production',
    cost: 1,
    vp: 1,
    goodType: 'indigo',
    count: 10,
    abilityText: 'ハーブを採集',
  },
  {
    id: 'sugar_mill',
    name: 'キノコ洞窟',
    type: 'production',
    cost: 2,
    vp: 1,
    goodType: 'sugar',
    count: 8,
    abilityText: 'キノコを採集',
  },
  {
    id: 'tobacco_storage',
    name: '蜂蜜場',
    type: 'production',
    cost: 3,
    vp: 2,
    goodType: 'tobacco',
    count: 8,
    abilityText: '蜜蝋を採集',
  },
  {
    id: 'coffee_roaster',
    name: '結晶鉱',
    type: 'production',
    cost: 4,
    vp: 2,
    goodType: 'coffee',
    count: 8,
    abilityText: '結晶を採集',
  },
  {
    id: 'silver_smelter',
    name: '月光の泉',
    type: 'production',
    cost: 5,
    vp: 3,
    goodType: 'silver',
    count: 8,
    abilityText: '月光石を採集',
  },

  // === 紫建物 (コスト1) ===
  {
    id: 'smithy',
    name: '魔法のるつぼ',
    type: 'violet',
    cost: 1,
    vp: 1,
    count: 3,
    ability: 'smithy',
    abilityText: '調合時: コスト-1',
  },
  {
    id: 'goldmine',
    name: '精霊の導き',
    type: 'violet',
    cost: 1,
    vp: 1,
    count: 3,
    ability: 'goldmine',
    abilityText: '探索時: 山札4枚公開、全て異なるコストなら1枚獲得',
  },
  {
    id: 'archive',
    name: '魔導書庫',
    type: 'violet',
    cost: 1,
    vp: 1,
    count: 3,
    ability: 'archive',
    abilityText: '占い時: 手札を任意に捨てられる',
  },

  // === 紫建物 (コスト2) ===
  {
    id: 'poor_house',
    name: '使い魔の巣',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'poor_house',
    abilityText: '調合後: 手札0-1枚なら1枚引く',
  },
  {
    id: 'black_market',
    name: '闇の市場',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'black_market',
    abilityText: '調合時: 素材1-2個を調合コストに使用可',
  },
  {
    id: 'trading_post',
    name: '旅商人の宿',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'trading_post',
    abilityText: '行商時: 追加で1個売却可能',
  },
  {
    id: 'well',
    name: '恵みの泉',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'well',
    abilityText: '採集時: 2個以上採集したら1枚引く',
  },
  {
    id: 'crane',
    name: '変容の術',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'crane',
    abilityText: '調合時: 既存設備の上に建て替え可能(差額のみ)',
  },
  {
    id: 'market_stand',
    name: '薬屋の露店',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'market_stand',
    abilityText: '行商時: 売却時に追加で1枚引く',
  },

  // === 紫建物 (コスト3) ===
  {
    id: 'chapel',
    name: '祈りの祭壇',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'chapel',
    abilityText: '毎ラウンド: 手札1枚を奉納(終了時1枚=1名声)',
  },
  {
    id: 'aqueduct',
    name: '魔法の水路',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'aqueduct',
    abilityText: '採集時: 追加で1個採集可能',
  },
  {
    id: 'carpenter',
    name: '工房の小妖精',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'carpenter',
    abilityText: '調合後: 1枚引く',
  },
  {
    id: 'prefecture',
    name: '千里眼の塔',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'prefecture',
    abilityText: '占い時: 追加で1枚保持可能',
  },
  {
    id: 'tower',
    name: '魔女の高塔',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'tower',
    abilityText: '手札上限が12枚になる',
  },
  {
    id: 'statue',
    name: '魔法の像',
    type: 'violet',
    cost: 3,
    vp: 3,
    count: 3,
    ability: 'monument',
    abilityText: '魔力のオブジェ (3名声)',
  },

  // === 紫建物 (コスト4) ===
  {
    id: 'market_hall',
    name: '大市場',
    type: 'violet',
    cost: 4,
    vp: 2,
    count: 3,
    ability: 'market_hall',
    abilityText: '行商時: 売却ごとに追加で1枚引く',
  },
  {
    id: 'victory_column',
    name: '魔力の柱',
    type: 'violet',
    cost: 4,
    vp: 4,
    count: 3,
    ability: 'monument',
    abilityText: '魔力のオブジェ (4名声)',
  },

  // === 紫建物 (コスト5) ===
  {
    id: 'hero',
    name: '大魔女',
    type: 'violet',
    cost: 5,
    vp: 3,
    count: 3,
    ability: 'hero',
    abilityText: '調合時: コスト6の設備を建てたら5枚引く',
  },
  {
    id: 'library',
    name: '禁断の書架',
    type: 'violet',
    cost: 5,
    vp: 3,
    count: 3,
    ability: 'library',
    abilityText: '仕事選択時: 他の紫設備の効果を2倍にする',
  },

  // === 紫建物 (コスト6) - 特殊得点 ===
  {
    id: 'city_hall',
    name: '魔女集会所',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'city_hall',
    abilityText: '終了時: 紫設備1つにつき+1名声',
  },
  {
    id: 'guild_hall',
    name: '素材商組合',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'guild_hall',
    abilityText: '終了時: 採集場1つにつき+2名声',
  },
  {
    id: 'palace',
    name: '魔女の城',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'palace',
    abilityText: '終了時: 他の名声4につき+1名声',
  },
  {
    id: 'triumphal_arch',
    name: '魔力の門',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'triumphal_arch',
    abilityText: '終了時: オブジェ1個=4, 2個=6, 3個+=8名声',
  },
];

export const CARD_DEF_MAP: Record<string, CardDef> = {};
for (const def of CARD_DEFS) {
  CARD_DEF_MAP[def.id] = def;
}
