import { CardDef } from './types';

export const CARD_DEFS: CardDef[] = [
  // === 生産建物 ===
  {
    id: 'indigo_plant',
    name: 'インディゴ染料工場',
    type: 'production',
    cost: 1,
    vp: 1,
    goodType: 'indigo',
    count: 10,
    abilityText: 'インディゴを生産',
  },
  {
    id: 'sugar_mill',
    name: '砂糖精製所',
    type: 'production',
    cost: 2,
    vp: 1,
    goodType: 'sugar',
    count: 8,
    abilityText: '砂糖を生産',
  },
  {
    id: 'tobacco_storage',
    name: 'タバコ保管庫',
    type: 'production',
    cost: 3,
    vp: 2,
    goodType: 'tobacco',
    count: 8,
    abilityText: 'タバコを生産',
  },
  {
    id: 'coffee_roaster',
    name: 'コーヒー焙煎所',
    type: 'production',
    cost: 4,
    vp: 2,
    goodType: 'coffee',
    count: 8,
    abilityText: 'コーヒーを生産',
  },
  {
    id: 'silver_smelter',
    name: '銀精錬所',
    type: 'production',
    cost: 5,
    vp: 3,
    goodType: 'silver',
    count: 8,
    abilityText: '銀を生産',
  },

  // === 紫建物 (コスト1) ===
  {
    id: 'smithy',
    name: '鍛冶屋',
    type: 'violet',
    cost: 1,
    vp: 1,
    count: 3,
    ability: 'smithy',
    abilityText: '建築時: コスト-1',
  },
  {
    id: 'goldmine',
    name: '金鉱',
    type: 'violet',
    cost: 1,
    vp: 1,
    count: 3,
    ability: 'goldmine',
    abilityText: '金鉱掘り時: 山札4枚公開、全て異なるコストなら1枚獲得',
  },
  {
    id: 'archive',
    name: '公文書館',
    type: 'violet',
    cost: 1,
    vp: 1,
    count: 3,
    ability: 'archive',
    abilityText: '参事会員時: 手札を任意に捨てられる',
  },

  // === 紫建物 (コスト2) ===
  {
    id: 'poor_house',
    name: '救貧院',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'poor_house',
    abilityText: '建築後: 手札0-1枚なら1枚引く',
  },
  {
    id: 'black_market',
    name: '闇市場',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'black_market',
    abilityText: '建築時: 商品1-2個を建築コストに使用可',
  },
  {
    id: 'trading_post',
    name: '商館',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'trading_post',
    abilityText: '商人時: 追加で1個売却可能',
  },
  {
    id: 'well',
    name: '井戸',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'well',
    abilityText: '生産時: 2個以上生産したら1枚引く',
  },
  {
    id: 'crane',
    name: 'クレーン',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'crane',
    abilityText: '建築時: 既存建物の上に建て替え可能(差額のみ支払い)',
  },
  {
    id: 'market_stand',
    name: '露店',
    type: 'violet',
    cost: 2,
    vp: 1,
    count: 3,
    ability: 'market_stand',
    abilityText: '商人時: 売却時に追加で1枚引く',
  },

  // === 紫建物 (コスト3) ===
  {
    id: 'chapel',
    name: '礼拝堂',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'chapel',
    abilityText: '毎ラウンド: 手札1枚を礼拝堂の下に格納(終了時1枚=1VP)',
  },
  {
    id: 'aqueduct',
    name: '水道橋',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'aqueduct',
    abilityText: '生産時: 追加で1個生産可能',
  },
  {
    id: 'carpenter',
    name: '大工小屋',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'carpenter',
    abilityText: '建築後: 1枚引く',
  },
  {
    id: 'prefecture',
    name: '知事官邸',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'prefecture',
    abilityText: '参事会員時: 追加で1枚保持可能',
  },
  {
    id: 'tower',
    name: '塔',
    type: 'violet',
    cost: 3,
    vp: 2,
    count: 3,
    ability: 'tower',
    abilityText: '手札上限が12枚になる',
  },
  {
    id: 'statue',
    name: '彫像',
    type: 'violet',
    cost: 3,
    vp: 3,
    count: 3,
    ability: 'monument',
    abilityText: '記念碑 (3VP)',
  },

  // === 紫建物 (コスト4) ===
  {
    id: 'market_hall',
    name: 'マーケットホール',
    type: 'violet',
    cost: 4,
    vp: 2,
    count: 3,
    ability: 'market_hall',
    abilityText: '商人時: 売却ごとに追加で1枚引く',
  },
  {
    id: 'victory_column',
    name: '凱旋門',
    type: 'violet',
    cost: 4,
    vp: 4,
    count: 3,
    ability: 'monument',
    abilityText: '記念碑 (4VP)',
  },

  // === 紫建物 (コスト5) ===
  {
    id: 'hero',
    name: '英雄',
    type: 'violet',
    cost: 5,
    vp: 3,
    count: 3,
    ability: 'hero',
    abilityText: '建築時: コスト6の建物を建てたら5枚引く',
  },
  {
    id: 'library',
    name: '図書館',
    type: 'violet',
    cost: 5,
    vp: 3,
    count: 3,
    ability: 'library',
    abilityText: '役職選択時: 他の紫建物の効果を2倍にする',
  },

  // === 紫建物 (コスト6) - 特殊得点 ===
  {
    id: 'city_hall',
    name: '市役所',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'city_hall',
    abilityText: '終了時: 紫建物1つにつき+1VP',
  },
  {
    id: 'guild_hall',
    name: 'ギルドホール',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'guild_hall',
    abilityText: '終了時: 生産建物1つにつき+2VP',
  },
  {
    id: 'palace',
    name: '宮殿',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'palace',
    abilityText: '終了時: 他の得点4VPにつき+1VP',
  },
  {
    id: 'triumphal_arch',
    name: '凱旋塔',
    type: 'violet',
    cost: 6,
    vp: 0,
    count: 2,
    ability: 'triumphal_arch',
    abilityText: '終了時: 記念碑1個=4VP, 2個=6VP, 3個+=8VP',
  },
];

export const CARD_DEF_MAP: Record<string, CardDef> = {};
for (const def of CARD_DEFS) {
  CARD_DEF_MAP[def.id] = def;
}
